### ISSUE TITLE
Wrong output to escaped character

### ISSUE THREAD

**Issue by alexander-akait** [css-modules/postcss-icss-selectors#108]
Input:
```css
.class { content: "\F10C" }
```
Output:
```css
.class { content: "\F10C" }
```
Seems works fine.

But wrong with lowercase.
Input:
```css
.class { content: "\f10C" }
```
Output:
```css
.class { content: "\F10C" }
```

I do not think it's true to change case of escaped character.
