### ISSUE TITLE
Global blocks?

### ISSUE THREAD

**Issue by geelen** [css-modules/postcss-icss-selectors#14]
Just porting my home page, came across my use of a reset, and considering my options. I'm really liking a full reset these days, but even normalise will have this problem.

Currently, you can either:
- go through and add `:global` to everything
- run a separate plugin chain that doesn't include local-by-default

I was thinking it might be handy to have a `:global` block syntax:

``` css
:global {
  html, body, div /* etc etc */ {
    margin: 0;
    padding: 0;
    border: 0;
    font-size: 100%;
    font: inherit;
    vertical-align: baseline;
  }
  /* etc etc */
}
```

Thoughts?
